### ISSUE TITLE
update to async dispatch?

### ISSUE THREAD

**Issue by idibidiart** [maximus8891/boilerplate-flux#1]
hey there

was looking into async dispatch and found this repo (And also another called quantum-flux) 

are you planning to update this boilerplate to replace flux dispatcher with your async dispatcher

also, given the obvious use cases for async dispatch (ajax callbacks, and unfreezing UI during heavy dispatch activity) why hasn't React team released an async dispatcher? curious.

thanks for sharing!
:)

**Comment by max-ch9i** [comment]
I will update it with the async disptacher shortly.
I'd appreciate if you could give it a whirl after it's done.

**Comment by idibidiart** [comment]
for sure! thx

**Comment by max-ch9i** [comment]
Implementing a solid async dispatcher requires serious consideration. The question that needs answering when processing actions: Would you still apply the second queued action after you see the outcome of the first queued action? Depending on the answer, you'd drop the second queued action or dispatch it anyway.

For example, if two async actions cause an update of two independed elements of the UI, then it's okay two apply them both.

Now consider the following scenario:
1. In an imaginary comment section to an imaginary invitation, you are about to leave a comment saying that you agree to join the event.
2. You press the 'Comment' button and it puts the action into the queue.
3. However, before you did that, someone left a comment saying they couldn't make it to the event, putting their action before yours.
4. Would you accept the invite without participation of the person who declined the invitation?

There are many ways to treat this scenario, like make a smart queue which would analyse its actions and have different resolutions depending on the actions' content.

**Comment by idibidiart** [comment]
The scenario doesn't make sense to me. The ajax callback that updates the status of participants (let's say the ajax call for updating the list is running via a timer) and let's say it gets on the action queue just as I click the comment button saying I'm attending. This has nothing to do with whether the dispatcher is sync or async since the second user has their own instance of the app.

The dispatcher is not a transaction engine. But I understand that if you mouseover 1000 bubbles on the screen in some data visualization and having to update some chart elsewhere on the screen or a tooltip that reflects the values implied by the bubble size (a data vis specific example) then dispatching synchronously would slow down the UI interaction leading to irresponsive UI as the dispatcher calls the event handlers in sequence and there is just one UI thread for all UI-bound actions to execute on. But if the dispatcher uses rAF  to assure at execute each UI-bound action (repaint) and spilt up the handler's worm (done by developer not the queue) if they go over the frame budget then you can have a good ux when it comes to UI interactivity.

So being able to queue the actions asynchronously and  execute them in order each within the frame budget (or have them be broken up at the handler level) then you will have a great solution to the problem of "no dispatch while another dispatch is happening" 

That's my understanding and I'm new to Flux implementations so maybe I am missing something?

**Comment by idibidiart** [comment]
See Async Actions in Redux, just found this:

http://rackt.org/redux/docs/advanced/AsyncActions.html

**Comment by max-ch9i** [comment]
The way you describe it is not async behaviour. That's why I prefer to call it 'queued', not async. The actions appear on the stack asynchronously, their dispatching is still synchronous.

http://rackt.org/redux/docs/advanced/AsyncActions.html
The example here is too simplistic. When you do an AJAX request to fetch data, you can easily whir a spinner and block the interaction. If you deal with websockets you can't do that, because you don't know when the next action hits the dispatcher. Coming back to our example, if you submit your comment and it reaches the server faster than the other person's one, it will mean that your action is the second on the queue for the person whoes action was slower to reach the server. It would make no sense to issue the third action on top of the second, as the state of the stores might change drastically after the second action dispatch. The dispatcher might be dumb and just dispatch it anyway letting the stores or the server take care of the mismatches in the comments order. Alternatively, the dispatcher might halt the dispatching and notify the stores with an action saying 'there are updates from the server, check your comment' or so.

For redux it's not a problem - there are no async dispatches, in fact they have no dispatcher: http://rackt.org/redux/docs/introduction/PriorArt.html. They just execute a function when the data comes back.

It's interesting that you say - 'the dispatcher is not a transactional engine'. In the Facebook Flux there's the waitFor method allowing to wait for one of the subscribed stores to update, before publishing to others, and it's implemented on the dispatcher level. It looks like a transactional aspect to me - controlling the order of store dispatching.
